CREATE TABLE IF NOT EXISTS components (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    team INTEGER NOT NULL,
    type VARCHAR  NOT NULL,
    language VARCHAR NOT NULL,
);
CREATE TABLE IF NOT EXISTS teams (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
);
CREATE  TABLE IF NOT EXISTS images (
    id INTEGER PRIMARY KEY,
    image BYTEA NOT NULL,
);
